baseURL = 'https://brodov.net/'
locale = 'ru-RU'
timeZone = 'Europe/Moscow'
defaultContentLanguage = 'ru'
title = 'Бродов нет'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
disableKinds = ['taxonomy', 'term']
[params]
  tagline = 'Журнал обыкновенных невероятностей'
  description = 'Журнал обыкновенных невероятностей. Истории из лесов и болот, заметки с кухни и рабочего стола.'
  author = 'Максим Скороход'
  contact = ''
  metrika_id = 112824105
[outputs]
  home = ['HTML', 'RSS']
[markup.goldmark.renderer]
  unsafe = false
[markup.highlight]
  noClasses = false
[imaging]
  resampleFilter = 'Lanczos'
[imaging.webp]
  quality = 85
[imaging.jpeg]
  quality = 85

[pagination]
  pagerSize = 10
[[module.mounts]]
  source = 'content'
  target = 'content'
[[module.mounts]]
  source = '.shorts-generated'
  target = 'content'
